# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Count number of times a sequence of numbers increases.
#'
#' @param values Vector of integers
#' @return The number of times subsequent value increases
#' @export
count_increases <- function(values) {
    .Call(`_aoc2021_count_increases`, values)
}

#' Count number of times a three-measurement sliding window increases in value.
#'
#' @param values Vector of integers
#' @return The number of times three measurement sliding window increases.
#' @export
window_increases <- function(values) {
    .Call(`_aoc2021_window_increases`, values)
}

#' Get the distance traveled from a set of commands.
#'
#' This is the result horizontal * result depth.
#'
#' @param commands Vector of commands for the submarine,
#'   e.g. forward 2, down 3 or up 5
#' @return The distance traveled by the submarine, resultant depth * horizontal
#' @export
total_distance <- function(commands) {
    .Call(`_aoc2021_total_distance`, commands)
}

#' Get the distance traveled from a set of commands for puzzle 2.
#'
#' This is the result horizontal * result depth.
#'
#' @param commands Vector of commands for the submarine,
#'   e.g. forward 2, down 3 or up 5
#' @return The distance traveled by the submarine, resultant depth * horizontal
#' @export
total_distance_2 <- function(commands) {
    .Call(`_aoc2021_total_distance_2`, commands)
}

#' Model fish internal timers for a number of days for some initial fish state.
#'
#' @param fish Vector of fish internal timers
#' @param days The number of days to run
#' @return The final state of fish internal timers
#' @export
model_fish <- function(fish, days) {
    .Call(`_aoc2021_model_fish`, fish, days)
}

#' Run a single day through fish timer.
#'
#' Take a vector of fish timers, reduce their values by 1 or if 0
#' reset timer to 6. If timer was reset, add a new fish to the end
#' with start timer of 8.
#'
#' @param fish Vector of fish internal timers
#' @return The final state of fish internal timers
#' @export
run_day <- function(fish) {
    .Call(`_aoc2021_run_day`, fish)
}

#' Count the number of fish after a number of days from some internal state
#'
#' @param fish Vector of fish internal timers
#' @param days The number of days to run
#' @return The final number of fish
#' @export
count_fish <- function(fish, days) {
    .Call(`_aoc2021_count_fish`, fish, days)
}

#' Count the number of fish after a number of days from some internal state
#'
#' @param fish Vector of fish internal timers
#' @param days The number of days to run
#' @return The final number of fish
#' @export
count_fish_class <- function(fish, days) {
    .Call(`_aoc2021_count_fish_class`, fish, days)
}

