# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Count number of times a sequence of numbers increases.
#'
#' @param values Vector of integers
#' @return The number of times subsequent value increases
#' @export
count_increases <- function(values) {
    .Call(`_aoc2021_count_increases`, values)
}

#' Count number of times a three-measurement sliding window increases in value.
#'
#' @param values Vector of integers
#' @return The number of times three measurement sliding window increases.
#' @export
window_increases <- function(values) {
    .Call(`_aoc2021_window_increases`, values)
}

#' Get the distance traveled from a set of commands.
#'
#' This is the result horizontal * result depth.
#'
#' @param commands Vector of commands for the submarine,
#'   e.g. forward 2, down 3 or up 5
#' @return The distance traveled by the submarine, resultant depth * horizontal
#' @export
total_distance <- function(commands) {
    .Call(`_aoc2021_total_distance`, commands)
}

#' Get the distance traveled from a set of commands for puzzle 2.
#'
#' This is the result horizontal * result depth.
#'
#' @param commands Vector of commands for the submarine,
#'   e.g. forward 2, down 3 or up 5
#' @return The distance traveled by the submarine, resultant depth * horizontal
#' @export
total_distance_2 <- function(commands) {
    .Call(`_aoc2021_total_distance_2`, commands)
}

#' Get the coordinates x1, y1, x2, y2 from input string of vent
#'
#' Takes vector of strings of format "0,9 -> 5,9" and parses to vector
#' of arrays
#'
#' @param commands Vector of commands for the submarine,
#'   e.g. forward 2, down 3 or up 5
#' @return The distance traveled by the submarine, resultant depth * horizontal
#' @export
get_coordinates <- function(vents) {
    .Call(`_aoc2021_get_coordinates`, vents)
}

#' Count dangerous areas from input string of vent paths
#'
#' @param vents Vent paths
#' @return The count of dangerous areas
#' @export
count_dangerous_areas <- function(vents) {
    .Call(`_aoc2021_count_dangerous_areas`, vents)
}

#' Count dangerous areas from input string of vent paths
#'
#' @param vents Vent paths
#' @return The count of dangerous areas
#' @export
count_dangerous_areas_2 <- function(vents) {
    .Call(`_aoc2021_count_dangerous_areas_2`, vents)
}

#' Model fish internal timers for a number of days for some initial fish state.
#'
#' @param fish Vector of fish internal timers
#' @param days The number of days to run
#' @return The final state of fish internal timers
#' @export
model_fish <- function(fish, days) {
    .Call(`_aoc2021_model_fish`, fish, days)
}

#' Run a single day through fish timer.
#'
#' Take a vector of fish timers, reduce their values by 1 or if 0
#' reset timer to 6. If timer was reset, add a new fish to the end
#' with start timer of 8.
#'
#' @param fish Vector of fish internal timers
#' @return The final state of fish internal timers
#' @export
run_day <- function(fish) {
    .Call(`_aoc2021_run_day`, fish)
}

#' Count the number of fish after a number of days from some internal state
#'
#' @param fish Vector of fish internal timers
#' @param days The number of days to run
#' @return The final number of fish
#' @export
count_fish <- function(fish, days) {
    .Call(`_aoc2021_count_fish`, fish, days)
}

#' Count the number of fish after a number of days from some internal state
#'
#' @param fish Vector of fish internal timers
#' @param days The number of days to run
#' @return The final number of fish
#' @export
count_fish_class <- function(fish, days) {
    .Call(`_aoc2021_count_fish_class`, fish, days)
}

#' Get the cost of aligning crabs to a particular position
#'
#' @param positions Vector of crab positions
#' @param alignment_position Final crab positions
#' @return The fuel cost of aligning to that position
#' @export
position_cost <- function(positions, alignment_position) {
    .Call(`_aoc2021_position_cost`, positions, alignment_position)
}

#' Get the lowest amount of fuel needed for all crabs to align.
#'
#' @param positions Vector of crab horizontal positions
#' @return The minimum fuel needed for the crabs to align
#' @export
optimal_position <- function(positions) {
    .Call(`_aoc2021_optimal_position`, positions)
}

#' Get the cost of aligning crabs to a particular position
#'
#' @param positions Vector of crab positions
#' @param alignment_position Final crab positions
#' @return The fuel cost of aligning to that position
#' @export
position_cost_2 <- function(positions, alignment_position) {
    .Call(`_aoc2021_position_cost_2`, positions, alignment_position)
}

#' Get the lowest amount of fuel needed for all crabs to align puzzle 2.
#'
#' @param positions Vector of crab horizontal positions
#' @return The minimum fuel needed for the crabs to align
#' @export
optimal_position_2 <- function(positions) {
    .Call(`_aoc2021_optimal_position_2`, positions)
}

#' Check if string b is in a, in any order.
#'
#' @param a superstring
#' @param b substring to test.
#' @return true if all characters in b are in a
#' @export
str_in <- function(a, b) {
    .Call(`_aoc2021_str_in`, a, b)
}

#' Remove characters of b from a.
#'
#' @param a string to remove from
#' @param b the string to remove
#' @return String a with characters from b removed
#' @export
str_diff <- function(a, b) {
    .Call(`_aoc2021_str_diff`, a, b)
}

#' Count the number of times 1, 4, 7 or 8 appear in log entries
#'
#' @param entries Log entries of form 10 signal patterns | delimitter and
#'   4 output values
#' @return The number of times 1, 4, 7 or 8 appear
#' @export
count_digits <- function(entries) {
    .Call(`_aoc2021_count_digits`, entries)
}

#' Count the number of times 1, 4, 7 or 8 appear in log entries
#'
#' @param entries Log entries of form 10 signal patterns | delimitter and
#'   4 output values
#' @return The number of times 1, 4, 7 or 8 appear
#' @export
sum_readings <- function(entries) {
    .Call(`_aoc2021_sum_readings`, entries)
}

