# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Count number of times a sequence of numbers increases.
#'
#' @param values Vector of integers
#' @return The number of times subsequent value increases
#' @export
count_increases <- function(values) {
    .Call(`_aoc2021_count_increases`, values)
}

#' Count number of times a three-measurement sliding window increases in value.
#'
#' @param values Vector of integers
#' @return The number of times three measurement sliding window increases.
#' @export
window_increases <- function(values) {
    .Call(`_aoc2021_window_increases`, values)
}

#' Get the error score from nav system.
#'
#' @param commands Vector of nav system entries
#' @return The syntax error score
#' @export
error_score <- function(nav_system) {
    .Call(`_aoc2021_error_score`, nav_system)
}

#' Get the autocomplete from nav system.
#'
#' @param commands Vector of nav system entries
#' @return The autocomplete score
#' @export
autocomplete_score <- function(nav_system) {
    .Call(`_aoc2021_autocomplete_score`, nav_system)
}

#' Count the number of times grid of octopuses flashed
#'
#' @param octopuses Grid of octopuses
#' @param steps The number of steps to run
#' @return The total number of times an octopus flashed
#' @export
get_flashes <- function(octopuses, steps) {
    .Call(`_aoc2021_get_flashes`, octopuses, steps)
}

#' Get the first day all octopuses flash
#'
#' @param octopuses Grid of octopuses
#' @param steps The number of steps to run
#' @return The first day all octopuses flash
#' @export
get_first_all_flash <- function(octopuses, steps) {
    .Call(`_aoc2021_get_first_all_flash`, octopuses, steps)
}

#' Get the total number of marked dots after folding
#'
#' @param input Puzzle input
#' @return Number of marked dots
#' @export
total_dots <- function(input) {
    .Call(`_aoc2021_total_dots`, input)
}

#' Print the text output from folding
#'
#' @param input Puzzle input
#' @export
print_output <- function(input) {
    invisible(.Call(`_aoc2021_print_output`, input))
}

#' Print the diff in size between most and least common element
#'
#' @param input Puzzle input
#' @export
polymer_size <- function(input, times) {
    .Call(`_aoc2021_polymer_size`, input, times)
}

#' Get the min risk of traversing risk grid
#'
#' @param risk Vector of vector of ints of risk of moving to a space
#' @return The minimum total risk
#' @export
get_min_risk <- function(risk) {
    .Call(`_aoc2021_get_min_risk`, risk)
}

#' Get the min risk of traversing full risk grid
#'
#' @param risk Vector of vector of ints of risk of moving to a space
#' @return The minimum total risk
#' @export
get_min_total_risk <- function(risk) {
    .Call(`_aoc2021_get_min_total_risk`, risk)
}

bin_to_int <- function(bin) {
    .Call(`_aoc2021_bin_to_int`, bin)
}

#' Sum version numbers of all packets
#'
#' @param input The packet hexadecimal
#' @return The sum of version numbers
#' @export
sum_version_numbers <- function(input) {
    .Call(`_aoc2021_sum_version_numbers`, input)
}

#' Get the value of package
#'
#' @param input The packet hexadecimal
#' @return The sum of version numbers
#' @export
get_package_value <- function(input) {
    .Call(`_aoc2021_get_package_value`, input)
}

#' Get the distance traveled from a set of commands.
#'
#' This is the result horizontal * result depth.
#'
#' @param commands Vector of commands for the submarine,
#'   e.g. forward 2, down 3 or up 5
#' @return The distance traveled by the submarine, resultant depth * horizontal
#' @export
total_distance <- function(commands) {
    .Call(`_aoc2021_total_distance`, commands)
}

#' Get the distance traveled from a set of commands for puzzle 2.
#'
#' This is the result horizontal * result depth.
#'
#' @param commands Vector of commands for the submarine,
#'   e.g. forward 2, down 3 or up 5
#' @return The distance traveled by the submarine, resultant depth * horizontal
#' @export
total_distance_2 <- function(commands) {
    .Call(`_aoc2021_total_distance_2`, commands)
}

#' Get the power consumption from set of bytes
#'
#' @param numbers Vector of binary numbers
#' @return The power consumption
#' @export
power_consumption <- function(numbers) {
    .Call(`_aoc2021_power_consumption`, numbers)
}

#' Get the life support rating from set of bytes
#'
#' @param numbers Vector of binary numbers
#' @return The life support rating
#' @export
life_support_rating <- function(numbers) {
    .Call(`_aoc2021_life_support_rating`, numbers)
}

#' Print the winning bingo score
#'
#' @param input Puzzle input
#' @export
winning_score <- function(input) {
    .Call(`_aoc2021_winning_score`, input)
}

#' Print the losing bingo score
#'
#' @param input Puzzle input
#' @export
losing_score <- function(input) {
    .Call(`_aoc2021_losing_score`, input)
}

#' Get the coordinates x1, y1, x2, y2 from input string of vent
#'
#' Takes vector of strings of format "0,9 -> 5,9" and parses to vector
#' of arrays
#'
#' @param commands Vector of commands for the submarine,
#'   e.g. forward 2, down 3 or up 5
#' @return The distance traveled by the submarine, resultant depth * horizontal
#' @export
get_coordinates <- function(vents) {
    .Call(`_aoc2021_get_coordinates`, vents)
}

#' Count dangerous areas from input string of vent paths
#'
#' @param vents Vent paths
#' @return The count of dangerous areas
#' @export
count_dangerous_areas <- function(vents) {
    .Call(`_aoc2021_count_dangerous_areas`, vents)
}

#' Count dangerous areas from input string of vent paths
#'
#' @param vents Vent paths
#' @return The count of dangerous areas
#' @export
count_dangerous_areas_2 <- function(vents) {
    .Call(`_aoc2021_count_dangerous_areas_2`, vents)
}

#' Model fish internal timers for a number of days for some initial fish state.
#'
#' @param fish Vector of fish internal timers
#' @param days The number of days to run
#' @return The final state of fish internal timers
#' @export
model_fish <- function(fish, days) {
    .Call(`_aoc2021_model_fish`, fish, days)
}

#' Run a single day through fish timer.
#'
#' Take a vector of fish timers, reduce their values by 1 or if 0
#' reset timer to 6. If timer was reset, add a new fish to the end
#' with start timer of 8.
#'
#' @param fish Vector of fish internal timers
#' @return The final state of fish internal timers
#' @export
run_day <- function(fish) {
    .Call(`_aoc2021_run_day`, fish)
}

#' Count the number of fish after a number of days from some internal state
#'
#' @param fish Vector of fish internal timers
#' @param days The number of days to run
#' @return The final number of fish
#' @export
count_fish <- function(fish, days) {
    .Call(`_aoc2021_count_fish`, fish, days)
}

#' Count the number of fish after a number of days from some internal state
#'
#' @param fish Vector of fish internal timers
#' @param days The number of days to run
#' @return The final number of fish
#' @export
count_fish_class <- function(fish, days) {
    .Call(`_aoc2021_count_fish_class`, fish, days)
}

#' Get the cost of aligning crabs to a particular position
#'
#' @param positions Vector of crab positions
#' @param alignment_position Final crab positions
#' @return The fuel cost of aligning to that position
#' @export
position_cost <- function(positions, alignment_position) {
    .Call(`_aoc2021_position_cost`, positions, alignment_position)
}

#' Get the lowest amount of fuel needed for all crabs to align.
#'
#' @param positions Vector of crab horizontal positions
#' @return The minimum fuel needed for the crabs to align
#' @export
optimal_position <- function(positions) {
    .Call(`_aoc2021_optimal_position`, positions)
}

#' Get the cost of aligning crabs to a particular position
#'
#' @param positions Vector of crab positions
#' @param alignment_position Final crab positions
#' @return The fuel cost of aligning to that position
#' @export
position_cost_2 <- function(positions, alignment_position) {
    .Call(`_aoc2021_position_cost_2`, positions, alignment_position)
}

#' Get the lowest amount of fuel needed for all crabs to align puzzle 2.
#'
#' @param positions Vector of crab horizontal positions
#' @return The minimum fuel needed for the crabs to align
#' @export
optimal_position_2 <- function(positions) {
    .Call(`_aoc2021_optimal_position_2`, positions)
}

#' Check if string b is in a, in any order.
#'
#' @param a superstring
#' @param b substring to test.
#' @return true if all characters in b are in a
#' @export
str_in <- function(a, b) {
    .Call(`_aoc2021_str_in`, a, b)
}

#' Remove characters of b from a.
#'
#' @param a string to remove from
#' @param b the string to remove
#' @return String a with characters from b removed
#' @export
str_diff <- function(a, b) {
    .Call(`_aoc2021_str_diff`, a, b)
}

#' Count the number of times 1, 4, 7 or 8 appear in log entries
#'
#' @param entries Log entries of form 10 signal patterns | delimitter and
#'   4 output values
#' @return The number of times 1, 4, 7 or 8 appear
#' @export
count_digits <- function(entries) {
    .Call(`_aoc2021_count_digits`, entries)
}

#' Count the number of times 1, 4, 7 or 8 appear in log entries
#'
#' @param entries Log entries of form 10 signal patterns | delimitter and
#'   4 output values
#' @return The number of times 1, 4, 7 or 8 appear
#' @export
sum_readings <- function(entries) {
    .Call(`_aoc2021_sum_readings`, entries)
}

#' Get the low points from heightmap
#'
#' @param map Heightmap
#' @return The low points in the heightmap
#' @export
get_low_points <- function(parsed) {
    .Call(`_aoc2021_get_low_points`, parsed)
}

#' Get the risk level from heightmap
#'
#' @param map Heightmap
#' @return The risk level
#' @export
risk_level <- function(map) {
    .Call(`_aoc2021_risk_level`, map)
}

#' Get the value of largest 3 basins multiplied together
#'
#' @param map height map
#' @return The size of 3 largest basins multiplied together
#' @export
basin_sizes <- function(map) {
    .Call(`_aoc2021_basin_sizes`, map)
}

